In [1]:
import numpy as np

In [2]:
s = np.array(5)

In [3]:
s

array(5)

In [4]:
s.shape

()

In [5]:
x = s + 3

In [6]:
x

8

In [7]:
v = np.array([1,2,3])

In [8]:
v

array([1, 2, 3])

In [9]:
v+x

array([ 9, 10, 11])

In [10]:
v.shape

(3,)

In [11]:
x = v[1]

In [12]:
x

2

In [13]:
v[1:]

array([2, 3])

In [14]:
m = np.array([[1,2,3], [4,5,6], [7,8,9]])

In [15]:
m.shape

(3, 3)

In [16]:
m[1][2]

6

In [35]:
t = np.array([[[[1],[2]],[[3],[4]],[[5],[6]]],[[[7],[8]],[[9],[10]],[[11],[12]]],[[[13],[14]],[[15],[16]],[[17],[17]]]])

In [36]:
t.shape

(3, 3, 2, 1)

In [38]:
t[1][2][1][0]

12

In [42]:
t

array([[[[ 1],
         [ 2]],

        [[ 3],
         [ 4]],

        [[ 5],
         [ 6]]],


       [[[ 7],
         [ 8]],

        [[ 9],
         [10]],

        [[11],
         [12]]],


       [[[13],
         [14]],

        [[15],
         [16]],

        [[17],
         [17]]]])

In [20]:
v = np.array([1,2,3,4])

In [21]:
v.shape

(4,)

In [22]:
x = v.reshape(1,4)

In [24]:
x.shape

(1, 4)

In [25]:
x

array([[1, 2, 3, 4]])

In [39]:
x = v.reshape(4,1)

In [41]:
x.shape

(4, 1)

In [43]:
x = v[None, :]

In [45]:
x.shape

(1, 4)

In [46]:
x = v[:, None]

In [47]:
x.shape

(4, 1)